import type { Config } from 'tailwindcss';

// Design tokens ported 1:1 from the approved Stitch / ui-ux-pro-max reference.
// Palette matches the shop banner: navy (primary) + red (secondary) + gold (tertiary).
const config: Config = {
  darkMode: 'class',
  content: [
    './src/app/**/*.{ts,tsx}',
    './src/components/**/*.{ts,tsx}',
    './src/lib/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#f1f4f6',
        'surface-bright': '#f7fafc',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#ffdea3',
        'on-secondary': '#ffffff',
        surface: '#f7fafc',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#b5c8e5',
        'inverse-surface': '#2d3133',
        'primary-fixed': '#d2e4ff',
        error: '#ba1a1a',
        'on-primary-container': '#7689a4',
        'surface-container-highest': '#e0e3e5',
        primary: '#000917',
        'on-primary-fixed-variant': '#364860',
        'primary-container': '#0d2137',
        'surface-variant': '#e0e3e5',
        'tertiary-fixed-dim': '#fdbc0a',
        'on-surface-variant': '#44474d',
        'on-secondary-fixed': '#410002',
        'secondary-fixed-dim': '#ffb4ab',
        tertiary: '#0e0800',
        'on-primary': '#ffffff',
        'on-error-container': '#93000a',
        'surface-container-lowest': '#ffffff',
        'outline-variant': '#c4c6cd',
        'surface-tint': '#4d6079',
        'tertiary-container': '#2c1e00',
        'on-primary-fixed': '#081c32',
        'on-tertiary-container': '#ae8000',
        'surface-container-high': '#e5e9eb',
        'inverse-on-surface': '#eef1f3',
        'inverse-primary': '#b5c8e5',
        'on-tertiary-fixed-variant': '#5d4200',
        background: '#f7fafc',
        'on-secondary-container': '#fffbff',
        'error-container': '#ffdad6',
        secondary: '#bb0114',
        'secondary-container': '#e02929',
        'on-background': '#181c1e',
        'on-tertiary-fixed': '#261900',
        'surface-container': '#ebeef0',
        'on-surface': '#181c1e',
        'surface-dim': '#d7dadc',
        'secondary-fixed': '#ffdad6',
        'on-secondary-fixed-variant': '#93000d',
        outline: '#74777d',
        // WhatsApp brand green for the floating button
        'whatsapp': '#25D366',
        'whatsapp-dark': '#128C7E',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        'section-padding': '120px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        'container-max': '1280px',
        base: '8px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        heading: ['var(--font-hanken)', 'Hanken Grotesk', 'system-ui', 'sans-serif'],
        body: ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
        // Semantic aliases kept from the reference so class names port cleanly.
        'display-lg': ['var(--font-hanken)', 'Hanken Grotesk', 'sans-serif'],
        'headline-lg': ['var(--font-hanken)', 'Hanken Grotesk', 'sans-serif'],
        'headline-lg-mobile': ['var(--font-hanken)', 'Hanken Grotesk', 'sans-serif'],
        'headline-md': ['var(--font-hanken)', 'Hanken Grotesk', 'sans-serif'],
        'label-bold': ['var(--font-hanken)', 'Hanken Grotesk', 'sans-serif'],
        'label-sm': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'body-md': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'body-lg': ['var(--font-inter)', 'Inter', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'display-lg': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};

export default config;
